### ISSUE TITLE
Friends get reseted after server restart

### ISSUE THREAD

**Issue by Greenman1805** [Nicewuerfel/BlockOwn#148]
The friends of all players get reseted after a server restart.

**Comment by Nicewuerfel** [comment]
Are there any errors in the console when stopping the server?

**Comment by Greenman1805** [comment]
yep http://pastebin.com/UhDDXpJJ

**Comment by Nicewuerfel** [comment]
OK, this will be solved, when #149 is resolved

**Comment by Greenman1805** [comment]
ok, thank you :)

**Comment by Nicewuerfel** [comment]
@Greenman1805 This build fixes the issue: https://pheasn-travis.s3.amazonaws.com/Nicewuerfel/BlockOwn/51/51.1/target/blockown-5.0.1-SNAPSHOT.jar

**Comment by Greenman1805** [comment]
Thanks!
