### ISSUE TITLE
Blocks get protected in worlds where blockown is not enabled...

### ISSUE THREAD

**Issue by Greenman1805** [Nicewuerfel/BlockOwn#150]
Blocks get protected in worlds where blockown is not enabled and when I set a block it throws a big exception. http://pastebin.com/PcLDq4BR

I have set:
  enabledWorlds:
    - Survival
  disabledWorlds: []

**Comment by Nicewuerfel** [comment]
@Greenman1805 Please try this build: https://pheasn-travis.s3.amazonaws.com/Nicewuerfel/BlockOwn/56/56.1/target/blockown-5.0.2-SNAPSHOT.jar

I hope the build fixes the (severe) bug, I tested it and didn't get any errors.
If the bug still exists in some form, the output should be more informative this time.

**Comment by Greenman1805** [comment]
Still an error:
http://pastebin.com/wmUhifXB

**Comment by Nicewuerfel** [comment]
I have rebuilt a lot of the database access which could solve the issue with the error spamming. 
I'm not 100% sure whether it fixes your issue since I couldn't reproduce it yet, but please try this build: https://pheasn-travis.s3.amazonaws.com/Nicewuerfel/BlockOwn/60/60.1/target/blockown-5.0.2-SNAPSHOT.jar

**Comment by Nicewuerfel** [comment]
I'm using a connection pool now (#151), this should solve the issue you probably had (the connection timing out). Try this build: https://pheasn-travis.s3.amazonaws.com/Nicewuerfel/BlockOwn/63/63.1/target/blockown-5.0.2-SNAPSHOT.jar

**Comment by Greenman1805** [comment]
I will try it!

**Comment by Greenman1805** [comment]
http://pastebin.com/2SGR5BRg :(

**Comment by Nicewuerfel** [comment]
Sorry, but it looks like you'll have to remove the world.db in the BlockOwn folder.

**Comment by Greenman1805** [comment]
But then all my protections are gone? o.o

**Comment by Nicewuerfel** [comment]
You could send me your world.db and I'll see if I can recover it...

**Comment by Greenman1805** [comment]
Where can I send it to you? Because it's 30MB big.

**Comment by Nicewuerfel** [comment]
Google Drive, Dropbox or (the easiest way) zip it and drag it into the comment field on this issue...

**Comment by Greenman1805** [comment]
[world.zip](https://github.com/Nicewuerfel/BlockOwn/files/166090/world.zip)

**Comment by Nicewuerfel** [comment]
I guess there was some data loss, but it seems like I could recover most of the data.
[recovered.zip](https://github.com/Nicewuerfel/BlockOwn/files/166111/recovered.zip)

**Comment by Greenman1805** [comment]
Thank you! I will try it and report future errors. :)
