### ISSUE TITLE
config gets reset

### ISSUE THREAD

**Issue by Greenman1805** [Nicewuerfel/BlockOwn#156]
I've set the config to:
  enabledWorlds:
    - Survival
  disabledWorlds: []

But after a restart these two points are empty like this:
  enabledWorlds: []
  disabledWorlds: []

**Comment by Nicewuerfel** [comment]
At the moment you can only change the config while the server is not running. I will fix that in the next few days.

**Comment by Greenman1805** [comment]
I edited the config while the server was stopped. Then I start the Server and all works fine the only world where it is enabled is Survival. But after a restart the StringList of enabledWorlds and disabledWorld gets resettet and I have to stop the server again to put Survival into the config :(

**Comment by Nicewuerfel** [comment]
@Greenman1805 I can't reproduce this issue with BlockOwn 5.3.2, could you provide a complete copy of your config.yml?

**Comment by Greenman1805** [comment]
[Configs.zip](https://github.com/Nicewuerfel/BlockOwn/files/190417/Configs.zip)

**Comment by Greenman1805** [comment]
Is there already a build with the fix?

**Comment by Nicewuerfel** [comment]
@Greenman1805  First of all, sorry that there was a development pause, I was on vacation in Denmark.

There is a build that only saves the config once on server start, not on server stop, so changes won't get overwritten ([download](https://pheasn-travis.s3.amazonaws.com/Nicewuerfel/BlockOwn/98/98.1/target/blockown-5.3.3-SNAPSHOT.jar)).
I still couldn't recreate your issue with the enabledWorlds/disabledWorlds lists getting reset, I will look further into that in a few days (probably April 4th, maybe earlier).

**Comment by Greenman1805** [comment]
This happens in the new version:
http://pastebin.com/P0Rit2Zf

**Comment by Nicewuerfel** [comment]
What server application (and version) are you using? (Craftbukkit, Spigot etc.)

**Comment by Greenman1805** [comment]
Spigot 1.8.9

**Comment by Greenman1805** [comment]
The new version works now.
BUT!
I stop the server and add Survival to the enabledWorld String List.
When I start the server after saving the file it gets cleared...

**Comment by Greenman1805** [comment]
I tried to add all worlds where it should be disabled in the disabledWorld list. After a restart 2 out of 8 worlds where left in the list, the others were gone.
Maybe there is a check when the plugin is started and it checks whether a world does exist or not and maybe there is an error?

**Comment by Greenman1805** [comment]
I made a fork and removed the config save method in the onEnable part and it works now :yum: 
Why is it nessesary to save the config?

**Comment by Nicewuerfel** [comment]
Sorry for the delay.
Saving the config is necessary for versions that make changes to it (adding new options, renaming one or so). However I did realize that at the moment the config is saved the enabled worlds are not loaded, since the plugin has to wait for other plugins (like Multiverse) to be loaded for that. There still is a small adjustment to be made, I will post a link to the fixed version here afterwars.

**Comment by Nicewuerfel** [comment]
[Here you go](https://pheasn-travis.s3.amazonaws.com/Nicewuerfel/BlockOwn/102/102.1/target/blockown-5.4-SNAPSHOT.jar)

**Comment by Greenman1805** [comment]
Nice, thank you for your help again!
