### ISSUE TITLE
Problem with enabledWorlds again

### ISSUE THREAD

**Issue by Greenman1805** [Nicewuerfel/BlockOwn#159]
After a Restart:
enabledWorlds: !!set {}
disabledWorlds: !!set {}

**Comment by Nicewuerfel** [comment]
Sorry about that, [it's fixed now.](https://pheasn-travis.s3.amazonaws.com/Nicewuerfel/BlockOwn/106/106.1/target/blockown-5.4.1-SNAPSHOT.jar)
